# Harmony Jekyll theme general configurations

# Base URL
baseurl:

# Site live URL
url: http://killianblais.fr

# Localhost
# url: http://127.0.0.1:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  name: killianblais.fr
  # Little description about your site
  # description: > #
  #  Mon petit coin sur internet
  meta_description: > #
   Mon blog de dev, sur PHP, Debian, et plein d'autres truc !
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Killian Blais
    email: contact@killianblais.fr
    url: http://killianblais.fr

  # Google Analytics key, leave blank to ignore
  # google_analytics_key: UA-xxxx-x

  # Profile links, leave blank to ignore
  social:
    github: blaiskillian
    twitter: killianblais
  # Toggle disclaimer in footer
  show_disclaimer: false

# Conversion / Build settings
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: pygments

# Permalinks
permalink:        pretty

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
