# Site settings
title: "killianblais.fr"
email: contact@killianblais.fr
description: "Blog d'un dev PHP Laravel, mais pas que..."
baseurl: ""
url: "http://killianblais.fr"
title_description: ""
title_image: "https://www.gravatar.com/avatar/f502004c5fbcd32e7b82db6f0973cf44?s=500&d=mm"
google_analytics:
disqus_account:
addthis_id:
post_limit: 5

# Social usernames/URLs
social:
  twitter_username: killianblais
  github_username:  blaiskillian
  instagram_username:
  reddit_username:
  linkedin_link:
  google_plus_link:
  stackoverflow_link:
  xing_link:
  facebook_link:

# Footer
footer_left: "Thème créé par <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "Blog hébergé sur <a href=\"https://github.com/kblais/blog\">Github</a>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
